### ISSUE TITLE
PEP deprecation note

### ISSUE THREAD

**Issue by synergiator** [dolfinus/setuptools-git-versioning#54]
Thank you for keeping up with this lib beyond the old version!

What's this warning?

```
Metadata 1.2 mandates PEP 440 version, but '.0.2-2021-02-08.post7-git.24d89ccf not
```

**Comment by dolfinus** [comment]
Hi.

Please provide your setup.py or pyproject.toml file

**Comment by synergiator** [comment]
hi, thanks for quick response - the setup.py looks like this.

```
"""Setup csextensions as a package."""
import setuptools

setuptools.setup(
    name="csextensions",
    # version="0.1.3",
    setuptools_git_versioning={
        "enabled": True,
        "version_format": "{tag}.dev{sha}",
        "starting_version": "0.1.3"
    },
    setup_requires=['setuptools-git-versioning'],
    url="https://gitlab.cc-asp.fraunhofer.de/fcs-public/apache-cs-extensions",
    description="Extensions for Apache Cloud Stack API CLI",
    long_description=open('README.rst').read(),

    packages=setuptools.find_packages(),

    install_requires=['paramiko', 'bs4', 'cs', 'beautifultable', 'python-dateutil'],

    classifiers=[
        'Development Status :: 2 - Pre-Alpha',
        'Programming Language :: Python',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.6',
        'License :: OSI Approved :: MIT License',
    ],
)

```

**Comment by dolfinus** [comment]
Could you please provide a `git log` output until the most recent tag?

**Comment by synergiator** [comment]
Alright let's replay this (the [repo](https://gitlab.cc-asp.fraunhofer.de/fcs-public/apache-cs-extensions/-/tags/v.0.3-testtag) is public so you should be to reproduce it, if needed):

1. do some commits
2. create a tag
3. extract git log
4. install the component as dependency to create the new output log

On my Ubuntu 22.04 machine, I use for this test venv/virtualenvwrapper with python3.10.4 and pip 22.1.

git log:
```
commit d4bbcb804a2bc1202c38887707c11cd7dd25849f (HEAD -> 4.13.x, origin/4.13.x)
Author: ...
Date:   Wed May 18 07:36:08 2022 +0200

    change runner tag

commit 7741640e594f2b468857cd8c153d6d98ba7d16f5 (tag: v.0.3-testtag)
Author: ...
Date:   Tue May 17 16:15:29 2022 +0200

    improved codes for network/vpc/tag primitives

commit 24d89ccf956e685ce565e8aeb5a3528bf28564da
Author: ....
Date:   Mon May 16 17:10:23 2022 +0200

    upgrade setup tools versioning for the installer

```

Installer output:
```
WARNING: Built wheel for csextensions is invalid: Metadata 1.2 mandates PEP 440 version, 
but '.0.3-testtag.post1-git.d4bbcb80' is not
Successfully built cs
Failed to build csextensions
Installing collected packages: ... done
  DEPRECATION: csextensions was installed using the legacy 'setup.py install' method, because a wheel 
could not be built for it. A possible replacement is to fix the wheel build issue reported above. 
Discussion can be found at https://github.com/pypa/pip/issues/8368
```
The installation seems to work nevertheless (?), as `pip list` contains this entry matching the latest commit (I work with venvs):
csextensions       .0.3-testtag.post1-git.d4bbcb80

## Python 3.9

**Comment by dolfinus** [comment]
If some tag is present in the current branch history, it is used as a base version, and then `.post$N+git.$COMMIT` suffix is added to it (`dev_template` option). Latest tag in your branch is `v.0.3-testtag`, it is used as a prefix. Leading `v` symbol is removed, because `v1.0.0` and `1.0.0` are the same versions, so you get `.0.3-testtag`, which is not a valid version number.

You should either:
1. Change this tag to a valid one, like `v0.3` or `0.3`.
2. Set up custom [dev_template](https://setuptools-git-versioning.readthedocs.io/en/stable/options/dev_template.html options, without using current tag as a substitution
3. Pass to [tag_formatter](https://setuptools-git-versioning.readthedocs.io/en/stable/options/tag_formatter.html) option some function which will convert `v.0.3-testing` tag to `0.3` version number

**Comment by synergiator** [comment]
thx!
