### ISSUE TITLE
How to write version info to `_version.py` file?

### ISSUE THREAD

**Issue by wxguy** [dolfinus/setuptools-git-versioning#76]
Thank you developers for making life easier with this package. No nonsense about future dev/ post string in the final name while creating the package. This is what I was exactly looking for. 

However, I wonder if I can write the version info in a separate file, so that version same version info is available in both development and installed mode. I am just looking at the option `write_to = "package-name_version.py"` being offered by `setuptools_scm` package. And solution or idea to make it possible is welcome.

Thank you.

**Comment by dolfinus** [comment]
Hi, thank you ☺️.

One of ideas this package is based on -  make no changes in the repo while calculating a version number. Writing generated version to a file requires either adding all the changes of this file into commit history (which causes merge conflicts), or adding this file to gitignore (no conflicts, but this requires to generate the file manually in a local repo).

That's why there is no such option in this project, and I hope it never be.

If you really need this, you can generate version number and export it to a file using bash redirect:
```bash
python setup.py --version > ./VERSION
```

But probably you need to look at this on another angle, for example to store version number in the file and then use it as a source for a package version:
* https://setuptools-git-versioning.readthedocs.io/en/stable/schemas/file/version_file.html
* https://setuptools-git-versioning.readthedocs.io/en/stable/options/count_commits.html

**Comment by wxguy** [comment]
Logical and fair enough.  I think this should be part of the main documentation in your site as it clears done fundemental question.

The problem I am facing here is that redirecting the version number at the time of GitHub release process makes the version to change from `x.x.x` to `x.x.x.post`. Is this also intended by the package? This causes the pypi build process to fail due to naming convention. Here is the simple release action workflow i am using https://github.com/wxguy/wrfplot/blob/main/.github/workflows/release-pip.yaml.

**Comment by dolfinus** [comment]
This is probably caused by the fact that file path you're saving current version to is not in the .gitignore. This leads to creating uncommitted changes in the local copy of a repo in Github runner, and thus setuptools-git-versioning generates not a release version but a dirty version:
https://setuptools-git-versioning.readthedocs.io/en/stable/schemas/tag/dirty_version.html
